# Nixpacks configuration for Railway
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "mkdir -p data/uploads data/cache data/logs data/backups",
  "touch data/uploads/.gitkeep data/cache/.gitkeep data/logs/.gitkeep data/backups/.gitkeep",
  "chmod -R 755 data/ public/"
]

[start]
cmd = "bash start.sh"
